### ISSUE TITLE
APNs error debugging

### ISSUE THREAD

**Issue by novavision** [industrialbinaries/lola#8]
Hi,
I experienced the problem setting up APNs in Firebase and found your tool to test it using terminal. By some reason it doesn't work and using lola I get this error in terminal
`Error: Invalid response Optional(<NSHTTPURLResponse: 0x7fa8efd18440> { URL: https://api.sandbox.push.apple.com:443/3/device/myDeviceFCMToken } { Status Code: 403, Headers {
    "apns-id" =     (
        "XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
    );`

Unfortunately I couldn't find any info about this error. Is there any way to get full error information using lola?

**Comment by jantimar** [comment]
Hello @novavision,

Thank you to create an issue. I have created PR where I add JSON response from APNs. https://github.com/industrialbinaries/lola/pull/9

Now your output in the terminal can look like this:
```
Error: Invalid response Optional(<NSHTTPURLResponse: 0x7f85a3458d40> { URL: https://api.sandbox.push.apple.com:443/3/device/d9f1767bdbf0371f5efb25c7873f1942cf570ececde9896913ed9fdb33ac1c26 } { Status Code: 400, Headers {
    "apns-id" =     (
        "1BC527FC-75EB-C93C-57EF-8CD208E9C3F5"
    );
} })

Data: {"reason":"DeviceTokenNotForTopic"}
```

Please look at the last line of your output where you should see the JSON response from APNs.

**Comment by novavision** [comment]
Hi,
Thanks for quick update. It works
